### ISSUE TITLE
VerifyChanges integrated with level and target in SwitchMultiLevel (and others)

### ISSUE THREAD

**Issue by Fishwaldo** [OpenZWave/open-zwave#1321]
We are at Version 3, Version 4 adds a Target Value Option in the report. It would be nice to update to this and incorporate into the Value::VerifyRefreshedValue Code

**Comment by AlCalzone** [comment]
See #1322 :)

**Comment by thoraxe** [comment]
@Fishwaldo @AlCalzone so is this issue (1321) closed since 1322 is merged?

**Comment by AlCalzone** [comment]
Seems so, but I can't close it.

**Comment by Fishwaldo** [comment]
Keeping it open as I want to integrate the target Value with the Refresh mechanisms. So the CC is updated but we can leverage a bit better internally

**Comment by thoraxe** [comment]
Ah gotcha.

I was having an issue with Home Assistant calling OZW and a dimmer switch. Basically the dimmer switch has a very slow ramp down from its max level (99) to its min level (0). OZW would stop refreshing the value before the dimmer hit 0 on the off cycle. This would result in Home Assistant thinking the dimmer was still on (val=34) when it was actually off.

There's an extra refresh setting in HA that has "fixed" this issue. But I feel like it's a workaround for what the OP of this issue is talking about -- HA/OZW doesn't look to see if we hit the "expected" value and thus we never go back to check if it ever got there.

The workaround:

```YAML
zwave:
  usb_path: /dev/zwave0
  network_key: !env_var ZWAVEKEY
  config_path: /usr/local/lib/python3.6/site-packages/python_openzwave/ozw_config/
  device_config:
    light.master_bedroom_light:
      refresh_value: true
```

This feels kinda like _oh it doesn't work right so I'll just poll_
