### ISSUE TITLE
fgfs-101 has wrong alert payload

### ISSUE THREAD

**Issue by anechiporuk** [OpenZWave/open-zwave#2408]
Hi, 

I have several flood sensors fibaro fgfs-101. They have 3 alerts, one of them has type(?) 48 and boolean value. Other two have type 156 and 0 value if everything is OK, and 255 in case of alert. But in descovery they advertise themselves in topic
homeassistant/binary_sensor/XXX/alarm_general/config
as
```
payload_on: true
payload_off: false
value_template: '{{ value_json.value }}'
device_class: problem
state_topic: XXX
json_attributes_topic: XXX
device:
  identifiers:
    - zwave2mqtt_0xfe026d2e_node14
  manufacturer: FIBARO System
  model: FGFS101 Flood Sensor (0x4001)
  name: XXX
  sw_version: '23.23'
name: XXX
unique_id: zwave2mqtt_0xfe026d2e_14-156-1-5
platform: mqtt
```

So, the problem is that payload_on and payload_off are wrong.

Also, alert with 48 type have the same payload values, but home-assistant discover page states that they must be strings, not boolean.
